name: Release Distribution

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Parse Changelog
        id: changelog
        uses: ocavue/changelog-parser-action@v1
        with:
          filePath: "CHANGELOG.md"
          removeMarkdown: false

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Make Gradle Wrapper executable
        run: chmod +x gradlew

      - name: Verify, Build, and Publish
        run: ./gradlew spotlessCheck check build publishPluginPublicationToHangar modrinth --no-daemon
        env:
          HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          RELEASE_CHANGELOG: ${{ steps.changelog.outputs.latestBody }}

      - name: Create GitHub Release & Upload Artifacts
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.latestBody }}
          files: build/libs/ClockTime*.jar
